; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Recovery Tool"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Trần Văn Hiếu (Brian)"
#define MyAppPublisherEmail "tranhieuglpk@gmail.com"
#define MyAppPublisherZalo "0335286360"
#define MyAppPublisherLinkedIn "https://www.linkedin.com/in/brian-tran1998/"
#define MyAppExeName "recovery_tool.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D37E90B0-F3E4-4B2E-B9D1-0A4E6C3B5E7A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppPublisherLinkedIn}
AppSupportURL={#MyAppPublisherEmail}
AppUpdatesURL={#MyAppPublisherLinkedIn}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=..\build\windows\installer
OutputBaseFilename=RecoveryToolInstaller
SetupIconFile=..\windows\runner\resources\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Messages]
WelcomeLabel2=This tool was developed by {#MyAppPublisher}.%n%nContact Info:%n- Email: {#MyAppPublisherEmail}%n- Zalo: {#MyAppPublisherZalo}%n- LinkedIn: {#MyAppPublisherLinkedIn}%n%nClick Next to continue with the installation.

[Code]
procedure InitializeWizard;
begin
  WizardForm.WelcomeLabel2.AutoSize := True;
end;
